# sqli_output.py

import json
import os
from datetime import datetime

class SQLiOutput:
    def __init__(self, payloads, output_dir="./output"):
        self.payloads = payloads
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def to_terminal(self):
        """Display payloads in terminal with formatting."""
        print("\n" + "="*60)
        print(" SQL INJECTION PAYLOADS".center(60))
        print("="*60)
        for idx, p in enumerate(self.payloads, 1):
            print(f" \n[{idx}]    Payload: {p['payload']}")
            print(f"DB: {p.get('database', 'N/A')} | Type: {p.get('type', 'N/A')}")
            
          

            if 'defense' in p:
                print(f"    🛡️ WAF: {p['defense']['waf']}")
                print(f"    🛡️ Filter: {p['defense']['filter']}")
                print(f"    🛡️ Validator: {p['defense']['validator']}")
                print(f"    🛡️ Why blocked: {p['defense']['why']}")
                print("\n" + "="*60)
            
            if 'encoded' in p:
                print(f"    Encoded: {p['encoded']}")
                print("\n" + "="*60)


            if 'obfuscated' in p:
                print(f"    Obf (comment): {p['obfuscated']['comment']}")
                print(f"    Obf (whitespace): {p['obfuscated']['whitespace']}")
                print(f"    Obf (mixed): {p['obfuscated']['mixed']}")
                print("\n" + "="*60)
                
      

        

    def to_json(self, filename=None):
        if not filename:
            filename = f"sqli_{self.timestamp}.json"
        else:
            filename = f"{filename}.json"
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w') as f:
            json.dump({
                "module": "sqli",
                "generated": self.timestamp,
                "count": len(self.payloads),
                "payloads": self.payloads
            }, f, indent=2)
        print(f"[+] JSON saved: {filepath}")

    def to_txt(self, filename=None):
        if not filename:
            filename = f"sqli_{self.timestamp}.txt"
        else:
            filename = f"{filename}.txt"
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w') as f:
            f.write(f"# SQLi Payloads - Generated by ITSOLERA Framework\n")
            f.write(f"# Date: {self.timestamp}\n\n")
            for p in self.payloads:
                f.write(p['payload'] + '\n')
        print(f"[+] TXT saved: {filepath}")

    def to_burp(self, filename=None):
        if not filename:
            filename = f"sqli_burp_{self.timestamp}.txt"
        else:
            filename = f"{filename}_burp.txt"
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w') as f:
            f.write(f"# Burp Intruder Payloads - SQLi\n")
            for p in self.payloads:
                f.write(p['payload'] + '\n')
        print(f"[+] Burp file saved: {filepath}")

    def to_zap(self, filename=None):
        if not filename:
            filename = f"sqli_zap_{self.timestamp}.txt"
        else:
            filename = f"{filename}_zap.txt"
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w') as f:
            f.write(f"# ZAP Fuzzer Payloads - SQLi\n")
            for p in self.payloads:
                f.write(p['payload'] + '\n')
        print(f"[+] ZAP file saved: {filepath}")